#!/bin/bash
cd $OPENSHIFT_REPO_DIR
mvn install -s $OPENSHIFT_DATA_DIR/maven/settings.xml -X
cp Transportation-ear/target/Transportation.ear $OPENSHIFT_DATA_DIR/glassfish4/glassfish/domains/domain1/autodeploy/





