#!/bin/bash
set -x
cd $OPENSHIFT_DATA_DIR
cp raw-domain.xml domain.xml_2
sed "s/$( grep serverName domain.xml_2 | cut -d\" -f 2 )/${OPENSHIFT_DIY_IP}/g" domain.xml_2 > domain.xml
rm domain.xml_2
mv domain.xml $OPENSHIFT_DATA_DIR/glassfish4/glassfish/domains/domain1/config/
export TZ="GMT"
$OPENSHIFT_DATA_DIR/glassfish4/glassfish/bin/asadmin start-domain &> $OPENSHIFT_DIY_LOG_DIR/start-server-"$(date)".log
cd $OPENSHIFT_REPO_DIR/.openshift/action_hooks
./post_deploy
