#!/bin/bash
set -x
#For test only
export OPENSHIFT_DIY_IP="127.0.0.1"
export OPENSHIFT_DATA_DIR="/home/youssef/GF4test"
export OPENSHIFT_DIY_LOG_DIR="/home/youssef/GF4test/log"

cd $OPENSHIFT_DATA_DIR
cp raw-domain.xml domain.xml_2
sed "s/$( grep serverName domain.xml_2 | cut -d\" -f 2 )/${OPENSHIFT_DIY_IP}/g" domain.xml_2 > domain.xml
pwd
mv domain.xml $OPENSHIFT_DATA_DIR/glassfish4/glassfish/domains/domain1/config/
export TZ="GMT"
$OPENSHIFT_DATA_DIR/glassfish4/glassfish/bin/asadmin start-domain &> $OPENSHIFT_DIY_LOG_DIR/start-server-"$(date)".log
