name: transpori
version: 0.5.0
description: Public transportation for everyone
dependencies:
  angular: 1.1.2
  angular_ui: any
  browser: any
  google_maps: any
  google_maps_angular:
    git:
      ref: 0.0.2
      url: https://github.com/youssefgh/angular-dart-google-maps.git
  observe: any
transformers:
- angular:
    html_files:
    - web/index.html
    - web/view/transportationRequest/view.html
